name: Generate Website

permissions:
  contents: write    # Needed for checkout and gh-pages deploy
  pages: write       # Needed for gh-pages deploy
  id-token: write    # May be needed depending on future interactions

on:
  repository_dispatch:
    types: [website-generation]

# Concurrency Control
concurrency:
  group: ${{ github.workflow }} # Group runs of THIS workflow
  cancel-in-progress: false    # Queue new runs instead of canceling old ones

jobs:
  generate-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js Dependencies
        run: npm install
        shell: bash

      - name: Compile Tailwind CSS
        # run: npx tailwindcss -i ./src/input.css -o ./python-service/templates/styles.css --minify
        run: npx tailwindcss -i ./src/input.css -o ./python-service/templates/styles.css --content "./python-service/templates/**/*.html" --minify
        shell: bash

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests jinja2 python-dotenv xmltodict flask
        shell: bash

      - name: Process website content & Copy Files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GITHUB_PAGES_TARGET: clickcatalyst-digital.github.io
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        # Execute the separate Python script instead of inline code
        run: python python-service/run_action_script.py
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./clients     # Deploy the whole 'clients' folder
          keep_files: true         # Keep existing files/folders
          commit_message: Deploy website for ${{ github.event.client_payload.folderName }}
